# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  persistCredentials: true
- script: |
             sudo apt-get install -y fonts-freefont-ttf
             ./gen.sh
             echo After convert call
  displayName: 'Generate images'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    git fetch
    curl https://screenshotbot.io/recorder.sh | sh
    ~/screenshotbot/recorder \
              --directory screenshots \
              --channel fast-example-azure \
              --main-branch master

  displayName: 'Run a multi-line script'
