# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
             sudo apt-get update
             sudo apt-get install -y imagemagick
             ./gen.sh
  displayName: 'Generate images'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    curl https://screenshotbot.io/recorder.sh | sh
    ~/screenshotbot/recorder \
              --directory screenshots \
              --channel fast-example \
              --production \
              --main-branch master \
              --api-key ${SCREENSHOTBOT_API_KEY} \
              --repo-url ${CIRCLE_REPOSITORY_URL} \
              --api-secret ${SCREENSHOTBOT_API_SECRET}

  displayName: 'Run a multi-line script'
