# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

  # We want to to be able to fetch the main branch even when we are
  # building for a Pull Request.
  persistCredentials: true

  # Screenshotbot doesn't work with shallow fetches. You can specify a
  # large number like 1000 here instead, and that should be good enough.
  fetchDepth: 0
- script: |
             sudo apt-get install -y fonts-freefont-ttf
             ./gen.sh
             echo After convert call
  displayName: 'Generate images'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    git fetch
    git show
    git status
    git log --all --max-count=10 '--pretty=%H %P'
    curl https://screenshotbot.io/recorder.sh | sh
    ~/screenshotbot/recorder \
              --directory screenshots \
              --channel fast-example-azure \
              --main-branch master \
              --commit-limit 10

  displayName: 'Run a multi-line script'
