version: 2
jobs:
  build:
    docker:
      - image: cimg/base:2020.01
        auth:
          username: tdrhq
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: |
             sudo apt-get update
             sudo apt-get install -y imagemagick
             ./gen.sh
             touch foo.txt
             git config --global user.email 'you@example.com'
             git config --global user.name 'Your Name'
             git add foo.txt
             git commit -m dummy

      - run:
          name: Record to screenshotbot
          command: |
            curl https://screenshotbot.io/recorder.sh | sh
            ~/screenshotbot/recorder \
              --directory screenshots \
              --channel fast-example \
              --production \
              --main-branch master \
              --api-key ${SCREENSHOTBOT_API_KEY} \
              --repo-url ${CIRCLE_REPOSITORY_URL} \
              --api-secret ${SCREENSHOTBOT_API_SECRET}
